### ISSUE TITLE
Add a Generic Direct Cast reminder button in the Community Page

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/votecaster#189]
TBD

Information by default in the DC:
- Personalized messaged by the host of the community
- Short message defined by Votecaster
- URL to the community

**Comment by elboletaire** [comment]
being done in #191

**Comment by ferranrego** [comment]
Text Improvements for the direct cast notifications modal:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/f368ae14-d325-4e4f-b1e5-bd63f8dd634c">

**Replace:**
Notify community members
**with**
Notify all community members

**Add under the title:**
Send a Direct Cast from your Farcaster account to all the members of your community.

**Replace:**
Append my community URL to the message
**with:** 
Add my community URL to the message

**Replace:**
Send notification
**with:**
Send
